"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var building_1 = require("../lib/building");
console.clear();
var map = (0, building_1.make_map)();
(0, building_1.add_place)(map, 'a', 1);
(0, building_1.add_place)(map, 'b', 1);
(0, building_1.add_place)(map, 'a_2', 2);
(0, building_1.add_place)(map, 'b_2', 2);
(0, building_1.add_place)(map, 'a_3', 3);
(0, building_1.add_place)(map, 'b_3', 3);
(0, building_1.add_path)(map, 'a', 'hallway_S', 'b');
(0, building_1.add_path)(map, 'a', 'hallway_S', 'b_3');
(0, building_1.add_path)(map, 'b', 'hallway_S', 'b_3');
(0, building_1.add_path)(map, 'a_2', 'hallway_S', 'b_2');
(0, building_1.remove_place)(map, 'a_2');
(0, building_1.add_place)(map, 'jenga', 5);
console.log(map);
console.log((0, building_1.check_empty)(map.nodes));
